/*

 DOWN_ARROW.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __down_arrow_h_INCLUDE
#define __down_arrow_h_INCLUDE

/* Bank of tiles. */
#define down_arrowBank 0
/* Start of tile array. */
extern const unsigned char down_arrow[];

#endif

/* End of DOWN_ARROW.H */
