/*

 HOMIE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char homie[] =
{
  0x00,0x00,0x00,0x18,0x00,0x24,0x00,0x42,
  0x00,0x42,0x00,0x42,0x00,0x24,0x00,0x18,
  0x00,0x3C,0x00,0x5A,0x00,0x5A,0x00,0x18,
  0x00,0x24,0x00,0x24,0x00,0x42,0x00,0x42
};

/* End of HOMIE.C */
