/*

 HOMER.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char homer[] =
{
  0x1C,0x00,0x3E,0x00,0x20,0x00,0x6A,0x4A,
  0x7E,0x20,0x20,0x1E,0x20,0x1C,0x18,0x00,
  0x09,0x00,0xC1,0x00,0xC1,0x00,0xC0,0x3F,
  0x00,0x7E,0x00,0x3E,0x00,0x36,0x77,0x77
};

/* End of HOMER.C */
