/*

 HOMIE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char homie[] =
{
  0x00,0x38,0x00,0x7C,0x78,0x04,0x54,0x52,
  0x04,0x02,0x7C,0x04,0x3C,0x18,0xDB,0x00,
  0xC3,0x00,0x83,0x00,0x83,0x00,0x03,0xFC,
  0x01,0x7E,0x00,0x7C,0x00,0x6C,0xEE,0xEE
};

/* End of HOMIE.C */
